Scrap Ontap
maciejkorolik/what-beers pull request #1
Opened 2022-07-14 10:39 UTC by maciejkorolik

2022-07-14 10:48 UTC, Zummek requested changes

2022-07-14 10:48 UTC, Zummek commented on index.js
> +      el.querySelector("h4.cml_shadow").textContent.replace(/\n|\r|\t/g, "")
Additionally, you can trim text

2022-07-14 10:48 UTC, maciejkorolik commented on index.js
> +      el.querySelector("h4.cml_shadow").textContent.replace(/\n|\r|\t/g, "")
👌

2022-07-14 11:07 UTC, RvuvuzelaM approved these changes
LGTM good stuff

2022-07-14 11:30 UTC, kasialorek approved these changes

2022-07-15 08:27 UTC, Zummek approved these changes

2022-07-15 08:30 UTC, merged